game/urls.py
#if you go to this URL, it shows you this view

from django.urls import path
from django.conf.urls import url

from . import views

#if someone types nothing, they'll go to the index view
app_name = 'game'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^game/$', views.game, name='game'),
]

gettingstarted/urls.py
from django.conf.urls import include, url
from django.urls import include, path

from django.contrib import admin
admin.autodiscover()

import hello.views

# Examples:
# url(r'^$', 'gettingstarted.views.home', name='home'),
# url(r'^blog/', include('blog.urls')),

urlpatterns = [
    url(r'^$', hello.views.index, name='index'),
    url(r'^db', hello.views.db, name='db'),
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
]

game/models.py
from django.db import models

# Create your models here.

hello/models.py
from django.db import models

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField('date created', auto_now_add=True)

skinpare/models.py
from django.db import models

# Create your models here.

game/views.py
#views are the pages

from django.shortcuts import render

from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'game/index.html', context)

def contact(request):
    context = {}
    return render(request, 'game/contact.html', context)

def game(request):
    context = {}
    return render(request, 'game/game.html', context)

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Greeting

# Create your views here.
def index(request):
    # return HttpResponse('Hello from Python!')
    return render(request, 'index.html')


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()

    return render(request, 'db.html', {'greetings': greetings})

skinpare/views.py
from django.shortcuts import render

# Create your views here.

game/templates/game/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-115199658-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-115199658-1');
	</script>

	<title>The Mouse with a Marble Nose</title>
	<meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<script type="text/javascript" src="{% static 'game/src/jQuery/jquery-3.3.1.min.js' %}"></script>
  <script type='text/javascript' src="{% static 'game/src/popper.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'game/src/bootstrap-v4/css/bootstrap.min.css' %}">
  <script type="text/javascript" src="{% static 'game/src/bootstrap-v4/js/bootstrap.min.js' %}"></script>
	<link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'game/styles/main.css' %}">
  {% block stylesheet %}{% endblock %}

</head>

<body>

  {% block body %}{% endblock %}

</body>
</html>

game/templates/game/contact.html
{% extends 'game/sidebar.html' %}
{% load static %}
{% block content %}

	<div class="container text-center">
	  <div class="row">
			<!--this is the right column-->
			<div class="col-12 col-sm-9 offset-sm-3 text-left">
				<div class="m-entry">
					<div class="m-h">A Bit about the Creator
					</div>
					<div class="m-p">
            <span class="m-imp-txt">Name:</span> Alexandra <br>
            <span class="m-imp-txt">Nickname:</span> Ali, Alex<br>
            <span class="m-imp-txt">Age:</span> Secret<br>
            <span class="m-imp-txt">Major:</span> MA in Global Intercultural Communications<br>
						<span class="m-imp-txt">Hobbies:</span> Singing, drawing, graphic design, sculpting, photography, web design/development, hand puppets<br><br>
            <span class="m-imp-txt">A blurb:</span> Hey there--Or perhaps I should say "howdy"? No. Anyway! I hope you like this very, very, very basic website. I put a lot of love into it, and edited it for hours on end. I jumped too quickly into Django/Heroku when I should have first made a site like this. It is WAY too overwhelming when you go from self-contained Codecademy lessons about HTML, CSS and Javascript to Django. <br>Just don't do it. <br><br>
            I hope you also like my game! It's only in the planning stages as of now, but the general concept/story was thought of two years ago now. I hope that doing this 'demo version' will be the motivation to starting the real thing.<br>
            I'd really love it if people gave me feedback on what they liked/disliked about it, so that I can implement it in the final version.<br><br>
						See below for contact information and future projects I'll be working on!
					</div>
				</div>
				<div class="m-entry">
					<div class="m-h">Contact
					</div>
					<div class="m-p">
						Email: <a href="mailto:alexarcra@gmail.com" target="_top">alexarcra@gmail.com</a><br><br>
						<div class="container" style="width: 100%;">
							<div class="row justify-content-center">
									<a href="https://medium.com/@al11"><img src="https://i.imgur.com/fcuiTYS.png"  class="m-c-icon"></a>
									<a href="https://www.instagram.com/airuri/"><img src="https://i.imgur.com/tP28Nch.png"  class="m-c-icon"></a>
									<a href="https://twitter.com/MarbleNoseMouse"><img src="https://i.imgur.com/Ywew9Xq.png"  class="m-c-icon"></a>
									<a href="https://www.linkedin.com/in/alii-cordes/"><img src="https://i.imgur.com/n4wcXMb.png"  class="m-c-icon"></a>
									<a href="https://www.facebook.com/Skinparison/"><img src="https://i.imgur.com/8I1CHNd.png"  class="m-c-icon"></a>
							</div>
						</div>
							<br>Personal website: It's literally <a href="https://arurie.github.io/mySite/index.html">this site</a><br>
							Company website: The domain name has been purchased, but for now links <a href="www.skinparison.com">here.</a><br><br>
							Maybe you loved my website so much, you want to throw me a testimonial on LinkedIn (I won't complain).<br>Or, if you enjoyed my story and would like to read more of my writing, you can follow my newly-made Medium page.<br>I'll be adding short stories to it now and then to practice for the final game.<br><br>If you're an experienced web developer and would like to discuss anything, please drop me a message on any of the above accounts.<br><br>Icons from <a href="http://www.iconninja.com/black-white-social-media-icon-sets-365">Icon Ninja</a>.
					</div>
				</div>
				<div class="m-entry">
					<div class="m-h">Future Projects
					</div>
					<div class="m-p">
						<h5 class="text-center">Business Concept</h5>
						<img class="card-img-top img-fluid" src="https://i.imgur.com/kxc0AVl.jpg" alt="Card image cap">
						<p class=""><br>This image is a very rough concept sketch of my future business website and its search function.<br><br>Two years ago, I had the idea for my business. Plagued by sensitive skin, trying products proved both a gamble and waste of money.Companies doned their products with a universal solution through the guise of 'suitable for sensitive skin'. More often than not, this was not the case.<br><br>I seek to simplify the process through community validation, and various technological frameworks I'm still afraid to speak too publicly about. In January 2018, I even <span class="m-imp-txt">won a pitch competiton</span> for a small amount of funding towards my idea. <br><br>I am now in the process of forming an application for further funding.</p>
					</div>
					<div class="m-p">
						<h5 class="text-center">Mascot Concept</h5>
						<img class="card-img-top img-fluid" src="https://i.imgur.com/aKm8qJg.jpg" alt="Card image cap">
						<p class=""><br>The main thing I've learned from talking to people about my business idea is that they want a sense of community, ease of use, and a feeling of welcomeness. That's just what this little guy/girl was created for! They will offer users interface help, and can even redirect them to videos if they so prefer.<br><br>They will be the size of a small marble in the bottom right corner of the website, and upon clicking, will enlarge to a medium overlay. This is when they will ask the user what they can help them with, or if they just want someone to talk to. This interaction may become like that of an NPC in a game, but for now, these are all just ideas.<br><br> They may even be customizable down the line, or have various incarnations due to localization concerns, but for now, they're a lovable circus dog/slug!</p>
					</div>
					<div class="m-p">
						<h5 class="text-center">Final Game</h5>
						<img class="card-img-top img-fluid" src="https://i.imgur.com/fss4NV1.png" alt="Card image cap">
						<p class="">Image Credit: <a href="http://kunlizhan.com/wp/">Kunli Zhan</a><br><br>The final game will not be browser-based, but will instead utilize Game Maker 2. This means the inclusion of gameplay, images, and music! Mechanics will be a mix of top-down RPG exploration interspersed with visual novel sections to highlight social interactions. Each character will have a schedule, so it will be the player's choice when to interact with them. That system will be complicated, so wish me luck!</p>
					</div>
					<div class="m-p">
						<h5 class="text-center">Personal Brand Card</h5>
						<img class="card-img-top img-fluid" src="https://i.imgur.com/F0YxnGO.jpg" alt="Card image cap">
						<p class=""><br>The above are front/back designs for business cards of my personal brand. My business' cards  will be a different design. <br><br>I've found recently that networking is key, though I still struggle to do so! Knowing who you are and marketing yourself is integral for not only building your own business, but finding things to be confident about, as well.</p>
					</div>
				</div>
			</div>

		</div>
		<div>
			<br>
		</div>
	</div>
{% endblock %}

game/templates/game/game.html
{% extends 'game/base.html' %}
{% load static %}
{% block stylesheet %}
<script src="{% static 'game/scripts/game.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="container">
      <div class="row">
        <div class="col" >
					<div class = "text-left">
						<a href="index.html" class="m-btn btn btn-secondary m-home">Home</a>
					</div>
            <div id="game-text" class="alert" role="alert">
            </div>

            <form autocomplete="off" id="game-form">
							<div class="form-group">
						    <input type="text" class="form-control" id="game-input" aria-describedby="game-input-help" placeholder="Press enter to continue" autofocus>
						  </div>
						</form>
        </div>
      </div>
    </div>
{% endblock %}

game/templates/game/index.html
{% extends 'game/sidebar.html' %}
{% load static %}
{% block content %}

	<div class="container text-center">
	  <div class="row">
			<!--this is the right column-->
			<div class="col-12 col-sm-9 offset-sm-3 text-left">
				<div class="m-entry">
					<div class="m-h">What is it?
					</div>
					<div class="m-p">
 						On an endless night, in a shut-off world, with the few who remain, your journey begins.
						You assume the identity of a nameless being, struggling to understand who or what they are.<br><br>
						Explore what little is left, and meet a colorful cast who may not all be as they appear.<br><br>
						This is a demo for a game I will be writing/developing in the next few years. The finished version will not be browser-based, or rely as heavily on text.<br>I hope you enjoy it nonetheless!
						The gameplay is inputting choices. For now, this is only for actions, but in the final version will extend to communication.<br><br>
						If you're familiar with visual novels or text adventures, that is the basic style this demo will be.
						This style was chosen because of both its simplicity for a short-term development, and because choosing how to communicate with others will be a key component with the themes presented.<br><br>
						Basically, communicating is difficult for a lot of people, and we aren't always able to see eye-to-eye. <br>
						Do your best to understand others, and make your motivations as clear as you can within the heavy constraints placed upon you. Good luck!
					</div>
				</div>
				<div class="m-entry">
					<p>
						<div class="m-h">Inspired By...
						</div>
						<div class="m-p">
							The inspiration for this game came from a year abroad, and the difficulties that brings. New places and dynamics are integral for gaining new perspectives and empathy, but some are better equipped to handle such situations than others. <br><br>This game is an exploration in navigating difficult social situations, where views differ and each party is equipped with their own memories, previous biases, reality filters, and baseline of understanding for any given situation.<br><br>Pssst, that's a fancy way of saying it's just like real-life interactions.
						</div>
					</p>
				</div>
				<div class="m-entry">
					<div class="m-h">Improving the Story Going Forward
					</div>
					<div class="m-p">
						If you're reading this after achieving a few endings in the demo, I hope you enjoyed it.<br><br>If anyone has input for how to make the story even better, be it characterization or pacing concerns, please email me at: <a href="mailto:alexarcra@gmail.com" target="_top">alexarcra@gmail.com</a>.<br>
					</div>
				</div>
				<div class="row">
					<br>
				</div>
			</div>

		</div>
	</div>
{% endblock %}

game/templates/game/sidebar.html
{% extends 'game/base.html' %}
{% load static %}
{% block body %}

	<!--this is the top bar-->
	<div class="m-topbar fixed-top text-center d-block d-sm-none">
		<a href="{% url 'game:game' %}" class="btn btn-secondary">Play Game</a>
		<a href="index.html" class="btn btn-dark">Home</a>
		<a href="contact.html" class="btn btn-secondary">About</a>
	</div>
	<div class="d-block d-sm-none">
		<br>
		<br>
	</div>

	<!--this is the sidebar-->
	<div class="m-fixed">
		<div class="container d-none d-sm-block">
			<div class="row">
				<div class="col-sm-3 text-center m-sidebar">
					<div class="">
						<div class="row">
							<br>
						</div>
						<img src="https://i.imgur.com/2nnc6CB.png" class="rounded-circle img-fluid" alt="Responsive image">
						<div class="row">
							<br>
						</div>
						<a href="{% url 'game:game' %}" class="btn btn-secondary">Play!</a>
						<div class="row">
							<br>
						</div>
						<a href="index.html" class="btn btn-dark">Home</a>
						<div class="row">
							<br>
						</div>
						<a href="contact.html" class="btn btn-secondary">About</a>
						<div class="row">
							<div style="width:60%; margin-left:20%;">
								<br>
								<a href="https://medium.com/@al11"><img src="https://i.imgur.com/fcuiTYS.png"  class="m-icon"></a>
								<a href="https://www.instagram.com/airuri/"><img src="https://i.imgur.com/tP28Nch.png"  class="m-icon d-md-none"></a>
								<a href="https://www.instagram.com/airuri/"><img src="https://i.imgur.com/KYHVw04.png"  class="m-icon d-none d-md-inline"></a>
								<a href="https://twitter.com/MarbleNoseMouse"><img src="https://i.imgur.com/zdblWvN.png"  class="m-icon"></a>
								<a href="https://www.linkedin.com/in/alii-cordes/"><img src="https://i.imgur.com/n4wcXMb.png"  class="m-icon d-md-none"></a>
								<a href="https://www.linkedin.com/in/alii-cordes/"><img src="https://i.imgur.com/hlD54oC.png"  class="m-icon d-none d-md-inline"></a>
								<a href="https://www.facebook.com/Skinparison/"><img src="https://i.imgur.com/y6h8elh.png"  class="m-icon"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

  {% block content %}{% endblock %}
{% endblock %}

hello/templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>Python Getting Started on Heroku</title>
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <style type="text/css">
    .jumbotron {
        background: #532f8c;
        color: white;
        padding-bottom: 80px
    }
    .jumbotron .btn-primary {
        background: #845ac7;
        border-color: #845ac7
    }
    .jumbotron .btn-primary:hover {
        background: #7646c1
    }
    .jumbotron p {
        color: #d9ccee;
        max-width: 75%;
        margin: 1em auto 2em
    }
    .navbar+.jumbotron {
        margin-top: -20px
    }
    .jumbotron .lang-logo {
        display: block;
        background: #b01302;
        border-radius: 50%;
        overflow: hidden;
        width: 100px;
        height: 100px;
        margin: auto;
        border: 2px solid white
    }
    .jumbotron .lang-logo img {
        max-width: 100%
    }


  </style>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav">
      <li class="active">
        <a href="/"><span class="glyphicon glyphicon-home"></span> Home</a>
      </li>
      <li>
        <a href="https://devcenter.heroku.com/articles/how-heroku-works"><span class="glyphicon glyphicon-user"></span> How Heroku Works</a>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-info-sign"></span> Getting Started Guides <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-ruby">Getting Started with Ruby on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-nodejs">Getting Started with Node on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-php">Getting Started with PHP on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-python">Getting Started with Python on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-java">Getting Started with Java on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-clojure">Getting Started with Clojure on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-scala">Getting Started with Scala on Heroku</a></li>
            <li class="divider"></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-heroku-and-connect-without-local-dev">Getting Started on Heroku with Heroku Connect</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-jruby">Getting Started with Ruby on Heroku (Microsoft Windows)</a></li>
          </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="navbar-right">
        <a href="https://devcenter.heroku.com"><span class="glyphicon glyphicon-book"></span> Heroku Dev Center</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}{% endblock %}

</body>
</html>

hello/templates/db.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container">


<h2>Page View Report</h2>


<ul>

{% for greeting in greetings %}
    <li>{{ greeting.when }}</li>
{% endfor %}

</ul>

</div>

{% endblock %}

hello/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="jumbotron text-center">
  <div class="container">
    <a href="/" class="lang-logo">
      <img src="{% static 'lang-logo.png'%}">
    </a>
    <h1>Getting Started with Python on Heroku</h1>
    <p>This is a sample Python application deployed to Heroku. It's a reasonably simple app - but a good foundation for understanding how to get the most out of the Heroku platform.</p>
    <a type="button" class="btn btn-lg btn-default" href="https://devcenter.heroku.com/articles/getting-started-with-python"><span class="glyphicon glyphicon-flash"></span> Getting Started with Python</a>
    <a type="button" class="btn btn-lg btn-primary" href="https://github.com/heroku/python-getting-started"><span class="glyphicon glyphicon-download"></span> Source on GitHub</a>
  </div>
</div>
<div class="container">
  <div class="alert alert-info text-center" role="alert">
    To deploy your own copy, and learn the fundamentals of the Heroku platform, head over to the <a href="https://devcenter.heroku.com/articles/getting-started-with-python" class="alert-link">Getting Started with Python on Heroku</a> tutorial.
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6">
      <h3><span class="glyphicon glyphicon-info-sign"></span> How this sample app works</h3>
      <ul>
        <li>This app was deployed to Heroku, either using Git or by using <a href="https://github.com/heroku/python-getting-started">Heroku Button</a> on the repository.</li>

        <li>When Heroku received the source code, it fetched all the dependencies in the <a href="https://github.com/heroku/python-getting-started/blob/master/Pipfile">Pipfile</a>, creating a deployable slug.</li>
        <li>The platform then spins up a dyno, a lightweight container that provides an isolated environment in which the slug can be mounted and executed.</li>
        <li>You can scale your app, manage it, and deploy over <a href="https://addons.heroku.com/">150 add-on services</a>, from the Dashboard or CLI.</li>
      </ul>
    </div>
    <div class="col-md-6">
      <h3><span class="glyphicon glyphicon-link"></span> Next Steps</h3>
      <ul>
        <li>If you are following the <a href="https://devcenter.heroku.com/articles/getting-started-with-python">Getting Started</a> guide, then please head back to the tutorial and follow the next steps!</li>
        <li>If you deployed this app by deploying the Heroku Button, then in a command line shell, run:</li>
        <ul>
          <li><code>git clone https://github.com/heroku/python-getting-started.git</code> - this will create a local copy of the source code for the app</li>
          <li><code>cd python-getting-started</code> - change directory into the local source code repository</li>
          <li><code>heroku git:remote -a &lt;your-app-name></code> - associate the Heroku app with the repository</li>
          <li>You'll now be set up to run the app locally, or <a href="https://devcenter.heroku.com/articles/getting-started-with-python#push-local-changes">deploy changes</a> to Heroku</li>
        </ul>
      </ul>
      <h3><span class="glyphicon glyphicon-link"></span> Helpful Links</h3>
      <ul>
        <li><a href="https://www.heroku.com/home">Heroku</a></li>
        <li><a href="https://devcenter.heroku.com/">Heroku Dev Center</a></li>
        <li><a href="https://devcenter.heroku.com/articles/getting-started-with-python">Getting Started with Python on Heroku</a></li>
        <li><a href="https://devcenter.heroku.com/articles/django-app-configuration">Configuring Django Apps for Heroku</a></li>
      </ul>
    </div>
  </div> <!-- row -->
   <div class="alert alert-info text-center" role="alert">
    Please do work through the Getting Started guide, even if you do know how to build such an application.  The guide covers the basics of working with Heroku, and will familiarize you with all the concepts you need in order to build and deploy your own apps.
  </div>
</div>
{% endblock %}